#!/usr/bin/env python
"""Write the redesigned portal router.py."""

lines = []

def L(line):
    lines.append(line)

L('"""Portal router.')
L('')
L('The Portal uses the same application-service operations, validation,')
L('authorization, concurrency, and audit behavior as the Core REST API.')
L('')
L('Portal handlers never access SQLite connections, repositories,')
L('arbitrary SQL, or database paths directly.')
L('"""')
L('')
L('from fastapi import APIRouter, Request, Header, Form, Cookie, Response')
L('from fastapi.responses import HTMLResponse')
L('from samjon_memory.portal.pages import (')
L('    render_portal_index,')
L('    render_memory_list,')
L('    render_memory_create,')
L('    render_memory_edit,')
L('    render_memory_detail,')
L('    render_collection_list,')
L('    render_collection_create,')
L('    render_collection_edit,')
L('    render_collection_detail,')
L('    render_audit_log,')
L('    render_message,')
L(')')
L('from samjon_memory.core.service import CoreService')
L('from samjon_memory.security.auth import get_current_token, get_admin_token')
L('from samjon_memory.errors import VersionConflict, NotFound, ValidationError')
L('from samjon_memory.constants import DEFAULT_PAGE_SIZE')
L('import uuid')
L('')
L('router = APIRouter()')
L('')
L('CSRF_COOKIE_NAME = "portal_csrf"')
L('READ_TOKEN_HEADER = "X-Service-Token"')
L('ADMIN_TOKEN_HEADER = "X-Admin-Token"')
L('CSRF_HEADER = "X-CSRF-Token"')
L('')
L('')
L('def _generate_csrf_token() -> str:')
L('    return uuid.uuid4().hex[:32]')
L('')
L('')
L('def _get_csrf_token(request: Request) -> str:')
L('    """Extract CSRF token from cookie or header."""')
L('    token = request.cookies.get(CSRF_COOKIE_NAME)')
L('    if not token:')
L('        token = _generate_csrf_token()')
L('    return token')
L('')
L('')
L('def _set_csrf_cookie(response: Response, token: str) -> None:')
L('    """Set CSRF token as SameSite=Strict cookie."""')
L('    response.set_cookie(')
L('        CSRF_COOKIE_NAME,')
L('        token,')
L('        httponly=True,')
L('        samesite="Strict",')
L('        max_age=3600,')
L('    )')
L('')
L('')
L('def _require_read_token(x_service_token: str = Header(None)) -> str:')
L('    """Require read-level authentication."""')
L('    return get_current_token(x_service_token)')
L('')
L('')
L('def _require_admin_token(x_admin_token: str = Header(None)) -> str:')
L('    """Require admin-level authentication for mutations."""')
L('    return get_admin_token(x_admin_token)')
L('')
L('')
L('def _get_service() -> CoreService:')
L('    """Create a fresh service instance per request."""')
L('')
L('')
L('@router.get("/portal/")')
L('async def portal_index(x_service_token: str = Header(None)):')
L('    """Portal home page - read access."""')
L('    _require_read_token(x_service_token)')
L('    service = _get_service()')
L('    return HTMLResponse(content=render_portal_index())')
L('')
L('')
L('@router.get("/portal/memories")')
L('async def portal_memories(')
L('    request: Request,')
L('    page: int = 1,')
L('    q: str = "",')
L('    x_service_token: str = Header(None),')
L('):')
L('    """List memories - read access."""')
L('    _require_read_token(x_service_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    memories = service.query_memories(subject=q, limit=DEFAULT_PAGE_SIZE, offset=(page - 1) * DEFAULT_PAGE_SIZE)')
L('    response = HTMLResponse(content=render_memory_list(memories, page, q, csrf_token))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('@router.get("/portal/memories/create")')
L('async def portal_memory_create_form(x_service_token: str = Header(None)):')
L('    """Show memory create form - admin access."""')
L('    _require_admin_token(x_service_token)')
L('    return HTMLResponse(content=render_memory_create())')
L('')
L('')
L('@router.post("/portal/memories/create")')
L('async def portal_memory_create(')
L('    request: Request,')
L('    subject: str = Form(...),')
L('')
L('')
L('@router.post("/portal/memories/{memory_id}/edit")')
L('async def portal_memory_edit(')
L('    request: Request,')
L('    memory_id: str,')
L('    subject: str = Form(None),')
L('    raw_content: str = Form(None),')
L('    expected_version: int = Form(None),')
L('    x_admin_token: str = Header(None),')
L('):')
L('    """Update a memory - admin access with version conflict protection."""')
L('    _require_admin_token(x_admin_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    try:')
L('        data = {}')
L('        if subject is not None:')
L('            data["subject"] = subject')
L('        if raw_content is not None:')
L('            data["raw_content"] = raw_content')
L('        if expected_version is not None:')
L('            data["expected_version"] = expected_version')
L('        memory = service.update_memory(memory_id, data)')
L('        msg = f"Memory {memory_id} updated to version {memory[\'version\']}."')
L('        response = HTMLResponse(content=render_message("Memory updated", msg, "success"))')
L('    except ValueError as e:')
L('        if "VERSION_CONFLICT" in str(e):')
L('            current = service.get_memory(memory_id)')
L('            warn = f"The memory was modified by another user. Current version is {current[\'version\']}. Please reload and retry."')
L('            response = HTMLResponse(content=render_message("Version Conflict", warn, "warning"))')
L('        else:')
L('            response = HTMLResponse(content=render_message("Error", str(e), "error"))')
L('    except NotFound as e:')
L('        response = HTMLResponse(content=render_message("Not Found", e.message, "error"))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('@router.post("/portal/memories/{memory_id}/supersede")')
L('async def portal_memory_supersede(')
L('    request: Request,')
L('    memory_id: str,')
L('    replacement_id: str = Form(...),')
L('    x_admin_token: str = Header(None),')
L('')
L('')
L('@router.get("/portal/collections")')
L('async def portal_collections(')
L('    request: Request,')
L('    page: int = 1,')
L('    q: str = "",')
L('    x_service_token: str = Header(None),')
L('):')
L('    """List collections - read access."""')
L('    _require_read_token(x_service_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    collections = service.list_collections(subject=q, limit=DEFAULT_PAGE_SIZE, offset=(page - 1) * DEFAULT_PAGE_SIZE)')
L('    response = HTMLResponse(content=render_collection_list(collections, page, q, csrf_token))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('@router.get("/portal/collections/create")')
L('async def portal_collection_create_form(x_service_token: str = Header(None)):')
L('    """Show collection create form - admin access."""')
L('    _require_admin_token(x_service_token)')
L('    return HTMLResponse(content=render_collection_create())')
L('')
L('')
L('@router.post("/portal/collections/create")')
L('async def portal_collection_create(')
L('    request: Request,')
L('    subject: str = Form(...),')
L('    title: str = Form(...),')
L('    source: str = Form("portal"),')
L('    expected_item_count: int = Form(None),')
L('    x_admin_token: str = Header(None),')
L('):')
L('    """Create a collection in draft state - admin access."""')
L('    _require_admin_token(x_admin_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    try:')
L('        collection = service.create_collection({')
L('            "subject": subject,')
L('            "title": title,')
L('            "source": source,')
L('            "expected_item_count": expected_item_count,')
L('        })')
L('        msg = f"Collection {collection[\'collection_id\']} created in draft state."')
L('        response = HTMLResponse(content=render_message("Collection created", msg, "success"))')
L('    except Exception as e:')
L('        response = HTMLResponse(content=render_message("Error", str(e), "error"))')
L('')
L('')
L('@router.post("/portal/collections/{collection_id}/edit")')
L('async def portal_collection_edit(')
L('    request: Request,')
L('    collection_id: str,')
L('    subject: str = Form(None),')
L('    title: str = Form(None),')
L('    expected_version: int = Form(None),')
L('    x_admin_token: str = Header(None),')
L('):')
L('    """Update collection metadata - admin access with version conflict protection."""')
L('    _require_admin_token(x_admin_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    try:')
L('        data = {}')
L('        if subject is not None:')
L('            data["subject"] = subject')
L('        if title is not None:')
L('            data["title"] = title')
L('        if expected_version is not None:')
L('            data["expected_version"] = expected_version')
L('        collection = service.update_collection(collection_id, data)')
L('        msg = f"Collection {collection_id} updated to version {collection[\'version\']}."')
L('        response = HTMLResponse(content=render_message("Collection updated", msg, "success"))')
L('    except ValueError as e:')
L('        if "VERSION_CONFLICT" in str(e):')
L('            current = service.get_collection(collection_id)')
L('            warn = f"The collection was modified by another user. Current version is {current[\'version\']}. Please reload and retry."')
L('            response = HTMLResponse(content=render_message("Version Conflict", warn, "warning"))')
L('        else:')
L('            response = HTMLResponse(content=render_message("Error", str(e), "error"))')
L('    except NotFound as e:')
L('        response = HTMLResponse(content=render_message("Not Found", e.message, "error"))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('@router.post("/portal/collections/{collection_id}/reorder")')
L('async def portal_collection_reorder(')
L('    request: Request,')
L('    collection_id: str,')
L('    ordered_memory_ids: str = Form(...),')
L('    x_admin_token: str = Header(None),')
L('):')
L('    """Reorder collection memories - admin access."""')
L('    _require_admin_token(x_admin_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    try:')
L('        ids = [mid.strip() for mid in ordered_memory_ids.split(",") if mid.strip()]')
L('        service.reorder_collection(collection_id, ids)')
L('        msg = f"Collection {collection_id} reordered."')
L('        response = HTMLResponse(content=render_message("Collection reordered", msg, "success"))')
L('')
L('')
L('@router.get("/portal/audit")')
L('async def portal_audit(')
L('    request: Request,')
L('    page: int = 1,')
L('    x_service_token: str = Header(None),')
L('):')
L('    """Audit log view - read access."""')
L('    _require_read_token(x_service_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    audits = service.get_audit_records(limit=DEFAULT_PAGE_SIZE, offset=(page - 1) * DEFAULT_PAGE_SIZE)')
L('    response = HTMLResponse(content=render_audit_log(audits, page, csrf_token))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('with open("src/samjon_memory/portal/router.py", "w", encoding="utf-8") as f:')
L('    f.write("\\n".join(lines))')
L('print("router.py written successfully")')
L('    except NotFound as e:')
L('        response = HTMLResponse(content=render_message("Not Found", e.message, "error"))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('@router.post("/portal/collections/{collection_id}/validate")')
L('async def portal_collection_validate(')
L('    request: Request,')
L('    collection_id: str,')
L('    x_admin_token: str = Header(None),')
L('):')
L('    """Validate collection - admin access."""')
L('    _require_admin_token(x_admin_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    try:')
L('        validation = service.validate_collection(collection_id)')
L('        issues_str = ", ".join(validation["issues"]) if validation["issues"] else "none"')
L('        level = "info" if validation["valid"] else "warning"')
L('        msg = f"Valid: {validation[\'valid\']}, Issues: {issues_str}, Memories: {validation[\'memory_count\']}"')
L('        response = HTMLResponse(content=render_message("Validation result", msg, level))')
L('    except NotFound as e:')
L('        response = HTMLResponse(content=render_message("Not Found", e.message, "error"))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('@router.post("/portal/collections/{collection_id}/activate")')
L('async def portal_collection_activate(')
L('    request: Request,')
L('    collection_id: str,')
L('    x_admin_token: str = Header(None),')
L('):')
L('    """Activate a collection - admin access, explicit activation."""')
L('    _require_admin_token(x_admin_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    try:')
L('        collection = service.activate_collection(collection_id)')
L('        msg = f"Collection {collection_id} is now {collection[\'status\']} at version {collection[\'version\']}."')
L('        response = HTMLResponse(content=render_message("Collection activated", msg, "success"))')
L('    except ValidationError as e:')
L('        response = HTMLResponse(content=render_message("Validation Error", e.message, "warning"))')
L('    except NotFound as e:')
L('        response = HTMLResponse(content=render_message("Not Found", e.message, "error"))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('@router.get("/portal/collections/{collection_id}")')
L('async def portal_collection_detail(')
L('    request: Request,')
L('    collection_id: str,')
L('    x_service_token: str = Header(None),')
L('):')
L('    """Collection detail with assembled preview - read access."""')
L('    _require_read_token(x_service_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    collection = service.get_collection(collection_id)')
L('    memories = service.get_collection_memories(collection_id, limit=100)')
L('    validation = service.validate_collection(collection_id)')
L('    response = HTMLResponse(content=render_collection_detail(collection, memories, validation, csrf_token))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('):')
L('    """Supersede a memory - admin access, guarded."""')
L('    _require_admin_token(x_admin_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    try:')
L('        service.supersede_memory(memory_id, replacement_id)')
L('        msg = f"Memory {memory_id} superseded by {replacement_id}."')
L('        response = HTMLResponse(content=render_message("Memory superseded", msg, "success"))')
L('    except NotFound as e:')
L('        response = HTMLResponse(content=render_message("Not Found", e.message, "error"))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('@router.post("/portal/memories/{memory_id}/forget")')
L('async def portal_memory_forget(')
L('    request: Request,')
L('    memory_id: str,')
L('    x_admin_token: str = Header(None),')
L('):')
L('    """Forget a memory - admin access, guarded."""')
L('    _require_admin_token(x_admin_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    try:')
L('        service.forget_memory(memory_id)')
L('        msg = f"Memory {memory_id} forgotten."')
L('        response = HTMLResponse(content=render_message("Memory forgotten", msg, "success"))')
L('    except NotFound as e:')
L('        response = HTMLResponse(content=render_message("Not Found", e.message, "error"))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('    raw_content: str = Form(...),')
L('    source: str = Form("portal"),')
L('    x_admin_token: str = Header(None),')
L('):')
L('    """Create a standalone memory - admin access."""')
L('    _require_admin_token(x_admin_token)')
L('    service = _get_service()')
L('    csrf_token = _get_csrf_token(request)')
L('    try:')
L('        memory = service.create_memory({')
L('            "subject": subject,')
L('            "raw_content": raw_content,')
L('            "source": source,')
L('        })')
L('        msg = f"Memory {memory[\'memory_id\']} created successfully."')
L('        response = HTMLResponse(content=render_message("Memory created", msg, "success"))')
L('    except Exception as e:')
L('        response = HTMLResponse(content=render_message("Error", str(e), "error"))')
L('    _set_csrf_cookie(response, csrf_token)')
L('    return response')
L('')
L('')
L('@router.get("/portal/memories/{memory_id}")')
L('async def portal_memory_detail(memory_id: str, x_service_token: str = Header(None)):')
L('    """Memory detail view - read access."""')
L('    _require_read_token(x_service_token)')
L('    service = _get_service()')
L('    memory = service.get_memory(memory_id)')
L('    return HTMLResponse(content=render_memory_detail(memory))')
L('')
L('')
L('@router.get("/portal/memories/{memory_id}/edit")')
L('async def portal_memory_edit_form(memory_id: str, x_service_token: str = Header(None)):')
L('    """Show memory edit form - admin access."""')
L('    _require_admin_token(x_service_token)')
L('    service = _get_service()')
L('    memory = service.get_memory(memory_id)')
L('    return HTMLResponse(content=render_memory_edit(memory))')
L('    return CoreService()')
